// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Category struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Priority struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Todo struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	PriorityID  int64  `json:"priority_id"`
	CategoryID  int64  `json:"category_id"`
}
